name: BOTTSLLSFS
on: [pull_request_target]

permissions:
  pull-requests: write

jobs:
  tagbot:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0


#    - name: Fetch target branch
#      run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
 
    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Git get
      run: pip install gitpython requests

    - name: Tag shit
      env:
        GH_TOKEN: ${{ secrets.TAGBOT_TEST }}
      run: |
          python .github/workflows/tagbot.py
